### ISSUE TITLE
Explicitly define action permissions

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge-docker#158]
I changed org defaults to not have read/write, so I think it's gonna need these perms now:

```yml
permissions:
  contents: read
  packages: write
```
