### ISSUE TITLE
upgrading from 2.7.1 to 3.0.0

### ISSUE THREAD

**Issue by pixelyo** [thelounge/thelounge-docker#75]
old (2.7.1) docker-compose:
```
lounge:
  image: thelounge/lounge:latest
  container_name: lounge
  ports:
    - "9000:9000"
  restart: always
  volumes:
- ~/.lounge:/home/lounge/data # bind lounge config from the host's file system
```

new (3.0.0) docker-compose:
```
version: '2'
services:
  thelounge:
    image: thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - "9000:9000"
    restart: always
    volumes:
- ~/.thelounge:/var/opt/thelounge # bind lounge config from the host's file system
```

when upgrading to 3.0.0: do only the image name and the docker internal volume path need to change?
